version: '3.8'

services:
  # Redis for rate limiting and sessions
  redis:
    image: redis:7-alpine
    container_name: pwa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  # PWA Application (Frontend + Backend)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pwa-web
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - SECRET_KEY=${SECRET_KEY}
      - SESSION_COOKIE_SECURE=False  # Set True with HTTPS
      - FORCE_HTTPS=False  # Set True in production with SSL/TLS
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5001}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5001/api/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
